---
app:
  route: www.delphi-council.org
  image:
    repo: quay.io/klenkes74
    name: delphi-council-webui
    tag: @project.version@
    pullPolicy: Always
  oidc:
    client: dcis-ui
    secret: hahaha
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi

api:
  route: api.delphi-council.org
  image:
    repo: quay.io/klenkes74
    name: delphi-council-service
    tag: @project.version@
    pullPolicy: Always
  oidc:
    client: dcis-api
    secret: hahaha
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi

oidc:
  url: https://sso.kaiserpfalz-edv.de/realms/delphi-council

db:
  local: false
  image:
    repo: docker-registry.default.svc:5000/openshift
    name: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
  storagesize: 2Gi
  host: mysql.loki.kaiserpfalz-edv.de
  port: 3306
  database: dcis
  rootpassword: changeme
  user: dcis
  password: changeme

mail:
  host:
    name: smtp.example.com
    port: 587
  user:
    name: Quin Sebastian
    address: quin.sebastian@delphi-council.org
    bounceaddress: support@paladins-inn.de
    user: clerk@delphi-council.org
    password: hahahaha
