#
# Copyright (c) 2021 Kaiserpfalz EDV-Service, Roland T. Lichti
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

quarkus:
  application:
    name: @project.name@
    version: @project.version@
    api-version: "v1"

  http:
    insecure-requests: enabled
    port: 8080
    ssl-port: 8443
    ssl:
      protocols: TLSv1.3
      sni: true

    access-log:
      enabled: true
      log-to-file: false
      exclude-pattern: "/q/.*"
      pattern: combined

    test-port: 8081
    test-ssl-port: 8444
    enable-compression: true
    enable-decompression: true
    record-request-start-time: true

    body:
      delete-uploaded-files-on-end: true
      handle-file-uploads: true
      preallocate-body-buffer: true
      merge-form-attributes: true

    auth:
      realm: ${quarkus.application.name}
      proactive: false
      policy:
        metrics:
          roles-allowed: metrics
      permission:
        protected:
          paths: /api/v1/*
          policy: authenticated
        metrics:
          paths: /q/*
          policy: metrics
        sw-js:
          paths: /sw.js
          policy: permit
    cors: true
  oidc:
    application-type: hybrid
    auth-server-url: ${OAUTH2_URL}
    client-id: ${OAUTH2_CLIENT}
    credentials:
      secret: ${OAUTH2_SECRET}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
  security:
    users:
      embedded:
        enabled: false


  datasource:
    db-kind: mariadb
    jdbc:
      ~: true
      url: "jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
      enable-metrics: true
      transactions: xa
    username: "${DB_USER:sa}"
    password: "${DB_PASSWORD:sa}"
    metrics:
      enabled: true
    devservices:
      enabled: true

  hibernate-orm:
    database:
      generation:
        ~: none
        create-schemas: false
        halt-on-error: true
    log:
      jdbc-warnings: true
      format-sql: true
      sql: true
      queries-slower-than-ms: 100

  hibernate-envers:
    store-data-at-delete: true

  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.xml


  mailer:
    host: "${MAIL_HOST:smtp.kaiserpfalz-edv.de}"
    port: "${MAIL_PORT:587}"
    ssl: true
    from: "${MAIL_FROM_NAME:Quin Sebastian} <${MAIL_FROM_ADDRESS:quin.sebastian@delphi-council.org}>"
    username: "${MAIL_USER:no}"
    password: "${MAIL_PASSWORD:no}"
    bounce-address: "${MAIL_BOUNCE_ADDRESS:tech@kaiserpfalz-edv.de}"
    keep-alive: true

  qute:
    property-not-found-strategy: throw_exception
    remove-standalone-lines: false
    strict-rendering: true

  log:
    metrics:
      enabled: true
    console:
      enable: true
      json: true
    level: WARN
    min-level: ALL
    category:
      "de.paladinsinn":
        level: INFO
      "de.kaiserpfalzedv":
        level: INFO
  logging-manager:
    enable: true
    ui:
      enable: true

  resteasy:
    problem:
      include-mdc-properties: workflow-id,step-id,application,version,node

  smallrye-health:
    ui:
      enable: true


  micrometer:
    enabled: true
    registry-enabled-default: true
    binder-enabled-default: true
    binder:
      http-server:
        enabled: true
        match-patterns: "/api/"
      mp-metrics:
        enabled: true
      jvm: true
      system: true
      vertx:
        enabled: true
    export:
      json:
        enabled: true
        path: /q/json-metrics
      prometheus:
        enabled: true
        path: /q/metrics
        default-registry: true

  smallrye-openapi:
    enable: true
    operation-id-strategy: method
    info: ${quarkus.application.name} API ${quarkus.application.api-version}
    info-version: ${quarkus.application.version}
    info-description: @project.description@
    info-terms-of-service: Service provided as is without any warranty
    info-contact-email: info@paladins-inn.de
    info-contact-name: Paladins Inn
    info-contact-url: https://www.paladins-inn.de
    info-license-name: GPL 3+
    info-license-url: http://www.gnu.org/licenses/

  swagger-ui:
    enable: true
    always-include: true


  container-image:
    name: @project.artifactId@
    tag: @project.version@
  openshift:
    deployment-kind: deployment

  devservices:
    enabled: true
  jaeger:
    enabled: true
  banner:
    enabled: true


"%dev":
  quarkus:
    datasource: &datasource-dev
      db-kind: h2
      jdbc:
        ~: true
        url: jdbc:h2:file:/Users/klenkes74/IdeaProjects/paladins-inn/delphi-council-is/target/db/delphi-council;USER=sa;PASSWORD=sa;MODE=MYSQL;PAGE_SIZE=512;TRACE_LEVEL_SYSTEM_OUT=0;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
        enable-metrics: true
      username: sa
      password: sa
    log: &log-dev
      console:
        json: false
        enable: true
      level: INFO
      min-level: ALL
      category:
        "de.kaiserpfalzedv":
          min-level: ALL
          level: DEBUG
        "de.paladinsinn":
          min-level: ALL
          level: DEBUG
    oidc: &oidc-dev
      enabled: false
    keycloak: &keycloak-dev
      policy-enforcer:
        enable: false
    security: &security-dev
      users:
        embedded:
          enabled: true
          plain-text: true
          realm-name: ${quarkus.application.name}
          users:
            player: player
            gm: gm
            orga: orga
            judge: judge
            admin: admin
            metrics: metrics
          roles:
            player: player
            gm: player,gm
            orga: player,gm,orga
            judge: player,gm,orga,judge
            admin: player,gm,orga,admin,metrics
            metrics: metrics


"%test":
  quarkus:
    datasource: *datasource-dev
    log: *log-dev
    oidc: *oidc-dev
    keycloak: *keycloak-dev
    security: *security-dev


