---
delphi-council:
  data-store: &dc_data
    url: ${DC_STORE_API}
    scope: javax.inject.Singleton

quarkus:
  rest-client:
    dispatch-api: *dc_data
    mission-report-api: *dc_data
    operative-api: *dc_data