---
delphi-council:
  data-store: &dc_data
    url: ${DC_STORE_API}
    scope: javax.inject.Singleton

quarkus:
  rest-client:
    dispatches-api: *dc_data
    engagements-api: *dc_data
    missions-api: *dc_data
    operatives-api: *dc_data