---
delphi-council:
  data-store: &dc_data
    url: ${DC_STORE_API}
    scope: javax.inject.Singleton

quarkus:
  rest-client:
    mission-api: *dc_data
    mission-report-api: *dc_data
    special-mission-api: *dc_data
    operative-api: *dc_data
    operative-report-api: *dc_data
    operative-special-report-api: *dc_data

  datasource:
    devservices:
      enabled: tru