---
kind: Secret
apiVersion: v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-db"
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: '2021-04-03T07:57:58Z'
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "db"
    app.kubernetes-io/part-of: "{{ .Chart.Name }}"
    app.kuberentes.io/managed-by: "helm"
type: Opaque
stringData:
  database-name: "{{ .Values.db.name }}"
  database-root-password: "{{ .Values.db.rootpassword }}"
  database-user: "{{ .Values.db.user}}"
  database-password: "{{ .Values.db.password }}"
