---
app:
  ingressClass: openshift-default
  route: www.delphi-council.org
  image:
    repo: quay.io/klenkes74
    name: @project.artifactId@
    tag: @project.version@
    pullPolicy: Always
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  name: dcis
  create: yes
  annotations: {}

podAnnotations:
  alpha.image.policy.openshift.io/resolve-names: '*'


tls:
  duration: 2160h
  renewBefore: 1800h

db:
  image:
    repo: image-registry.openshift-image-registry.svc:5000/openshift
    name: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
  storagesize: 2Gi
  name: dcis
  rootpassword: changeme
  user: dcis
  password: changeme

mail:
  host:
    name: smtp.example.com
    port: 587
  user:
    name: Quin Sebastian
    address: quin.sebastian@delphi-council.org
    user: clerk@delphi-council.org
    password: hahahaha
