{{- if .Values.serviceAccount.create -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.serviceAccount.name }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
