---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-app-cert"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  commonName: "{{ .Values.app.route }}"
  dnsNames:
    - "{{ .Values.app.route }}"
  uris:
    - "{{ .Values.app.route }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: "{{ .Chart.Name }}-app-tls"
  duration: {{ .Values.tls.duration }}
  renewBefore: {{ .Values.tls.renewBefore }}
  usages:
  - server auth