---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-app-cert"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  secretName: "{{ .Chart.Name }}-app-tls"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
  - server auth
  commonName: "{{ .Values.app.route }}"
  dnsNames:
    - "{{ .Values.app.route }}"
  uris:
    - "{{ .Values.app.route }}"
  duration: 2160h
  renewBefore: 1488h
