# FIXME 2022-12-27 rlichti Needs to be converted from v1alpha1
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-app-cert"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  acme:
    config:
      - dns01:
          provider: kaiserpfalz-edv
        domains:
          - "{{ .Values.app.route }}"
          - "{{ .Values.api.route }}"
  commonName: "{{ .Values.app.route }}"
  dnsNames:
    - "{{ .Values.app.route }}"
    - "{{ .Values.api.route }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: "{{ .Chart.Name }}-tls"
