---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-app"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
spec:
  ingressClassName: {{ .Values.app.ingressClass }}
  rules:
  - host: "{{ .Values.app.route }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: "{{ .Chart.Name }}"
            port:
              number: 8080
  tls:
  - hosts:
    - "{{ .Values.app.route }}"
    secretName: "{{ .Chart.Name }}-app-tls"
