# FIXME 2022-12-27 rlichti Needs to be converted from v1beta1 to release CRD
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-app"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
spec:
  rules:
  - host: "{{ .Values.app.route }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Chart.Name }}-app"
          servicePort: 8443
  tls:
  - hosts:
    - "{{ .Values.app.route }}"
    secretName: "{{ .Chart.Name }}-tls"
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-api"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
spec:
  rules:
    - host: "{{ .Values.api.route }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ .Chart.Name }}-api"
              servicePort: 8443
  tls:
    - hosts:
        - "{{ .Values.api.route }}"
      secretName: "{{ .Chart.Name }}-tls"
