## This is basic continuous integration build for your Quarkus application.

name: CI

on:
  push:
    branches: [ development,main ]

jobs:
  java-build:
    runs-on: [ java ]
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Remove node_modules package-lock.json and package.json
        id: prepare-npm
        run: rm -rf node_modules package-lock.json package.json
      - name: Build
        id: build-java
        run: mvn package -B -Pproduction
      - name: Upload Artifact
        env:
          IMAGE: $(cat target/classes/Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')
          VERSION: $(cat target/classes/Dockerfile | grep APP_VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g')
        id: upload-jar
        uses: actions/upload-artifact@v2
        with:
          name: dci
          path: |
            target/delphi-council-is-${{ env.VERSION }}.jar
            target/classes/Dockerfile
          retention-days: 1
  container-build:
    runs-on: [ podman ]
    needs: java-build
    steps:
      - name: checkout sources
        id: checkout-sources
        uses: actions/checkout@v2
      - name: retrieve jar and dockerfile
        id: retrieve-jar
        uses: actions/download-artifact@v2
        with:
          name: dci
      - name: Buildah
        env:
          IMAGE: $(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')
          VERSION: $(cat Dockerfile | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g')
        id: build-container
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE }}
          tags: ${{ env.VERSION }} latest ${{ github.sha }}
          dockerfiles: |
            ./Dockerfile
      - name: Push To quay
        env:
          IMAGE: $(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')
          VERSION: $(cat Dockerfile | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g')
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}
          tags: ${{ env.VERSION }} latest ${{ github.sha }}
          registry: ${{ secrets.QUAY_REPO }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Use the image
        run: echo "New image has been pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
