## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ development,main ]
  pull_request:
    branches: [ development,main ]
  workflow_dispatch:
    branches: [ development,main ]

jobs:
  build:
    runs-on: [ java ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: mvn package -B
